name: Run Robot Framework Tests

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version your tests require

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework

    - name: Run Robot Framework tests
      run: |
        robot test.robot  # Adjust the command if your test file or command differs
