name: Run Robot Framework Tests

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version your tests require

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Install Google Chrome
      run: |
        curl -LO https://dl.google.com/chrome/mac/universal/chrome-mac-universal.dmg
        brew install --cask google-chrome
        brew install nss


    - name: Download and set up ChromeDriver
      run: |
        curl -LO https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.99/mac-arm64/chromedriver-mac-arm64.zip
        unzip chromedriver-mac-arm64.zip
        chmod +x chromedriver-mac-arm64/chromedriver
        sudo mv chromedriver-mac-arm64/chromedriver /usr/local/bin/chromedriver

    - name: Prepare directories
      run: |
        mkdir -p screenshots
        mkdir -p Results

    - name: Run Robot Framework tests
      run: |
        robot Test.robot

    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      with:
          name: screenshots
          path: screenshots/

    - name: Check out repo again for pushing
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: Test

    - name: Copy screenshots to repo
      run: |
        cp -r /Users/runner/work/Test/Test/screenshots/ Results/screenshots_new/
        cp -r /Users/runner/work/Test/Test/* Results/
      working-directory: Test


    - name: Commit and push screenshots to repoo
      run: |
        cd Test
        git config user.name "jeanpaulatallah"
        git config user.email "jeanpaulatallah@github.com"
        git add Results/screenshots_new/
        git add Results/
        git commit -m "Add screenshots from workflow"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
