name: Run Robot Framework Tests

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version your tests require

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Download and set up ChromeDriver
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.99/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/chromedriver

    - name: Run Robot Framework tests
      run: |
        robot Test.robot
