name: Run Robot Framework Tests

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version your tests require

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Install Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get update
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
        sudo apt-get install -y libnss3


    - name: Download and set up ChromeDriver
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.99/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo chmod +x chromedriver-linux64/chromedriver
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver

    - name: Verify Chrome and ChromeDriver
      run: |
        google-chrome --version
        chromedriver --version


    - name: Run Robot Framework tests
      run: |
        robot Test.robot
